### ISSUE TITLE
dominant and highlight colors not correct

### ISSUE THREAD

**Issue by delta1071** [Wartybix/GNOME-Auto-Accent-Colour#21] opened 2024-12-03 20:47 UTC
Running latest version of AAC in Ubuntu 24.10 (GNOME 47) with ImageMagick 7.1.1-41 compiled from source. AAC shows IM and rsvg2-bin as available. The two screenshots attached show my desktop background (a .jpg file) which is predominantly blue, and my system tray buttons using AAC's 'Dominant' setting (and BTW changing to 'Highlight' does not change the color). It seems that the 'Dominant'  setting should bring a blueish color, not orange.

![Screenshot From 2024-12-03 15-37-02](https://github.com/user-attachments/assets/3f267927-34c7-49f3-b069-1856aa3995ff)
![Screenshot From 2024-12-03 15-34-32](https://github.com/user-attachments/assets/cd530b19-1295-4d0e-a271-16523df69464)

**Comment by Wartybix** [comment] 2024-12-04 00:19
Okay, this is interesting behaviour. I just ran AAC on the screenshot of the wallpaper on my system, and I think I may have found a bug, though I'm not yet sure if its related to your original issue.

This is what the 'Paleta' app outputs as the colour palette of this image: (16, 39, 63) as the 'dominant' colour, and (244, 147, 152) as the 'highlight' colour. So blue should very much be derived as the 'dominant' colour for this background, with orange/pink being the 'highlight' colour.
![image](https://github.com/user-attachments/assets/c9326587-7a7a-42a1-86cc-8b853f045d68)

Like Auto Accent Colour, Paleta uses ColorThief to extract colours from images, so colours returned by Paletta *should* be exactly the same as those derived in AAC, and this is the case with most images I've tested. But when I run AAC on my machine on it, it returns (72, 245, 51) as the 'dominant' colour (which is converted to the green accent), and (42, 69, 249) as the 'highlight' colour (converted to the blue accent when I switch to highlight mode).
```
Hash of background in /home/wartybix/.config/background is 3723852225...
Background image format: image/png
Conversion to JPG required: false
Cache miss: recomputing palette...
Wallpaper colour palette: 72,245,51,42,69,249,250,23,57,17,40,64,222,226,146,0
Palette: 72,245,51,42,69,249...
Getting dominant accent...
Parsed hue: 113.50515463917526
Parsed saturation: 79.18367346938776
Distance from green: 10701
Closest accent: green
Accent to apply: green
New accent: green
```
So this is not behaving as expected as 1) the palette derived isn't the same as the palette returned in Paletta, and 2) I don't see any kind of green in this image, let alone it being the 'dominant' colour.

What's interesting though, is if I convert this PNG file to a JPG with `magick test.png test.jpg`, and set the JPG as my background, AAC *will* derive the same colours as Paletta (within the decimal-rounding margin of error), and apply a blue 'dominant' accent. It'll also apply a pink 'highlight' accent when the option is selected.
```
Hash of background in /home/wartybix/.config/background is 1498389327...
Background image format: image/jpeg
Conversion to JPG required: false
Cache miss: recomputing palette...
Wallpaper colour palette: 16,39,63,243,147,152,26,187,224,21,131,205,48,92,130,0
Palette: 16,39,63,243,147,152...
Getting dominant accent...
Parsed hue: 210.63829787234042
Parsed saturation: 74.60317460317461
Distance from blue: 38641
Distance from teal: 83776
Distance from slate: 49238
Closest accent: blue
Accent to apply: blue
New accent: blue
```

So using the JPG conversion meets the expected behaviour. This leads me to believe I made a mistake when porting ColorThief into AAC which only affects PNG files (I reproduced this issue with other PNG files too).

But I'm still not sure whether this 'PNG bug' is related to your issue of the extension being too keen on orange. I'm not sure why this would be the case since you said the original wallpaper is a JPG file.

Could you please:
1) Go to the extension preferences, and enable 'Disable Cache' in Debug settings.
2) Enable 'Debug Logging' in the same page.
3) With the problematic wallpaper applied, click the 'Force Refresh' option within AAC's panel indicator (you may need to unhide it if you previously hid it via the Settings tab).
4) Once that's done, open the 'Logs' app from your app launcher.
5) Navigate to the 'All' tab on the side, and search for 'Colour'. There should be at least one row for Auto Accent Colour that can be clicked on to expand. Screenshot the latest run of AAC from the top and attach it in a reply. It should look slightly like this:
![image](https://github.com/user-attachments/assets/49462783-190b-498b-896e-6d930a34c729)
6) In this reply, please could you also attach a copy of the original wallpaper (not a screenshot of it). If you're not sure where it is, you can find its path in the terminal with ```gsettings get org.gnome.desktop.background picture-uri``` (or `picture-uri-dark` if using dark mode). This is so I can test with the exact same background image as you to see if I can replicate the behaviour.

Thanks for opening this issue and letting me know of the problem. Also, glad to see your last issue was resolved and ImageMagick is now detected :grin:.

**Comment by Wartybix** [comment] 2024-12-08 00:23
Hello,

I published a new version (11) to the GNOME extensions store yesterday that might fix your problem. Please let me know if your problem is resolved, otherwise I will close this issue as completed in a couple of weeks' time.

**Closed** 2024-12-17 00:54 UTC
Labels: bug, question
